barryvdh-laravel-ide-helper:
	php artisan ide-helper:generate
	php artisan ide-helper:models --nowrite
	php artisan ide-helper:meta

fruitcake-laravel-debugbar:
	php artisan vendor:publish --provider='Fruitcake\LaravelDebugbar\ServiceProvider'

spatie-laravel-permission:
	php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider"
	php artisan config:clear
	php artisan migrate

.DEFAULT:
	@echo "No post-install actions for target: $@"