#!/bin/bash

info "$(basename "${BASH_SOURCE[0]}")" "Setting permissions..."

USER=$USER

# 1. Eigenaar en groep goedzetten
sudo chown -R "$USER:www-data" "$PROJECT_ROOT"

# 2. Mappen: 775 en SGID bit (drwxrwsr-x)
# De 'X' zorgt ervoor dat mappen wel het execute-bit krijgen (nodig om erin te gaan)
sudo find "$PROJECT_ROOT" -type d -exec chmod 2775 {} +

# 3. Bestanden: Standaard naar 664 (-rw-rw-r--)
sudo find "$PROJECT_ROOT" -type f -exec chmod 664 {} +

# 4. maak cache en logmappen toegankelijk
sudo chmod -R 777 "$PROJECT_ROOT/storage" "$PROJECT_ROOT/bootstrap/cache"

message="Permissions are set for '$PROJECT_ROOT'"

return 0
