#!/bin/bash

# process input
PROJECT_NAME_UNDERSCORED=$(echo "$PROJECT_NAME" | tr '-' '_') 

DB_NAME="${PROJECT_NAME_UNDERSCORED}_db"
DB_USER=$PROJECT_NAME_UNDERSCORED
DB_PASSWORD="${PROJECT_NAME_UNDERSCORED}@mysql"

TEST_DB_NAME="${PROJECT_NAME_UNDERSCORED}_test_db"
TEST_DB_USER=$PROJECT_NAME_UNDERSCORED
TEST_DB_PASSWORD="${PROJECT_NAME_UNDERSCORED}@mysql"

SERVER_NAME="${PROJECT_NAME}.local"

TEST_DB_SNIPPET=$(cat "$FRAMEWORK_SNIPPETS_DIR/test-db-sqlite.txt")
